[package]
name = "lab-1"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
plotters = "0.3.4"
plotters-backend = "0.3.4"
log = "0.4.17"
